### ISSUE TITLE
Page not found on link 

### ISSUE THREAD

**Issue by DylanMeeus** [paypal/paypal.github.com#32] opened 2019-04-30 23:03 UTC
Hey,

This page: https://www.paypal.com/us/webapps/mpp/logos-buttons
has a link to generate a JS PayPal button at the bottom. It says: (Create a Javascript Button)

However, this points to a page that no longer exists: http://paypal.github.io/JavaScriptButtons/

**Comment by hozefaj** [comment] 2019-05-01 04:17
@DylanMeeus Thanks for pointing it out. We will update the link to the correct one.

**Comment by hozefaj** [comment] 2019-05-08 17:13
@DylanMeeus The issue is now fixed. @lmarkus You can close this issue.

**Closed** 2019-05-08 19:31 UTC
